language: c
dist: xenial
services:
- xvfb
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/linux_install_os_dependencies_for_testing_on_ubuntu.sh; fi
install:
- nvm install 8 --lts
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- nvm use 8
- yarn --version
- nvm --version
- node --version
- yarn
script: true
stages:
- name: prescript
  if: branch IN (ci) AND commit_message !~ /^appveyor Updating branch from appveyor
    build.$/
- name: lint
  if: "(branch IN (master, ci, testci, develop) AND commit_message !~ /^appveyor Updating
    branch from appveyor build.$/) OR type == pull_request OR tag =~ /^v\\\\d+\\\\.\\\\d+(\\\\.\\\\d+)?(-\\\\S*)?$/"
- name: unittest
  if: branch IN (master) OR type IN (pull_request)
- name: unittestandcoverage
  if: branch IN (ci, testci) AND commit_message !~ /^appveyor Updating branch from
    appveyor build.$/
- name: test
  if: type IN (pull_request) OR (branch IN (ci, testci, master) AND commit_message
    !~ /^appveyor Updating branch from appveyor build.$/)
- name: build
  if: tag =~ ^v\d+\.\d+(\.\d+)?(-\S*)?$
jobs:
  include:
  - stage: prescript
    os: osx
    before_script: "./scripts/ci_merge_script.sh"
    script: yarn
  - os: linux
    before_script: "./scripts/ci_merge_script.sh"
    script: yarn
  - stage: lint
    os: osx
    script: yarn run lint
  - os: linux
    script: yarn run lint
  - stage: unittest
    os: osx
    script: yarn run unit
  - os: linux
    script: yarn run unit
  - stage: unittestandcoverage
    os: osx
    script:
    - yarn run unit
    - yarn run unit:coverage
  - os: linux
    script:
    - yarn run unit
  - stage: test
    os: osx
    script: yarn run e2e:impl test/features/backlog
  - os: linux
    script: yarn run e2e:impl test/features/backlog
  - os: osx
    script: yarn run e2e:impl test/features/data_curator
  - os: linux
    script: yarn run e2e:impl test/features/data_curator
  - os: osx
    script: yarn run e2e:impl test/features/edit
  - os: linux
    script: yarn run e2e:impl test/features/edit
  - os: osx
    script: yarn run e2e:impl test/features/file
  - os: linux
    script: yarn run e2e:impl test/features/file
  - os: osx
    script: yarn run e2e:impl test/features/find
  - os: linux
    script: yarn run e2e:impl test/features/find
  - os: osx
    script: yarn run e2e:impl test/features/help
  - os: linux
    script: yarn run e2e:impl test/features/help
  - os: osx
    script: yarn run e2e:impl test/features/other
  - os: linux
    script: yarn run e2e:impl test/features/other
  - os: osx
    script: yarn run e2e:impl test/features/support
  - os: linux
    script: yarn run e2e:impl test/features/support
  - os: osx
    script: yarn run e2e:impl test/features/tools
  - os: linux
    script: yarn run e2e:impl test/features/tools
  - os: osx
    script: yarn run e2e:impl test/features/window
  - os: linux
    script: yarn run e2e:impl test/features/window
  - stage: build
    os: osx
    script:
    - yarn run clean
    - yarn run release:predraft
env:
  global:
  - secure: Ed4mhHGlgrZDt7Qu/NpkszYYgzYJc9PGXRJPA39CLz6eVD+SpmDz19mjAB0oTrLtFNPcJlSsT8ocZvvTAH+AtCIi5BvWFcLlT5z2DcLluATlSdS7zrTGHYudJmcKOwYgOvmV+zhwo7KCkkVS+7VA0kQx5x+Oa1ftvQmVuA4gD5RYhLBh9JK6ugEyMpr1nMhrkuHkZmmEn5oy2btZSAwyY6PQ3c26iDrXq9NMqWk0kQtN3LiLwTqYoxIiK0Vo8hYi0AOpZ2BmWFSZAtmIj4NE6YFn2u6qtsG26v/3qLybJr/FZBGlvQRurRP3IEa58ilNcEBhMPjAHKNijng30AHXMrteLmY4obZV+/bEwmaHwYd5DbNtl5YPv2/3+Dlw86IUNzhwktaw/qyZYdlXDsVjiE8wK+Qs73lIOtBz8oekORtzorf/snvQVXTyF6QeGCrfy1uGymXwHMA5tbOXXShIxqMXOFELbCq++iHZyOvV4OZAbgbWe84B1o2e5eQ+IkyO7YgBTUzCK7HT0EDA+bhnB8aZP6G+hLXc73tiV0vEkcrpt3YHsiT68YwTo9KwdC8iVV7+/7dUNcNsj5NQRvOxp5riVmivwNpY4gvJsVr/UB98A+iUfMm0si5e/eceu7hwGkQh2+ITDXdMBtls7Lhb66T58KZR7UiQsmv2/xyTe78=
  - secure: BfulWFgDZ1hDL9CAyVVIrjjIqSut6sKt3fzWIexJg8+XomCkCi7rpsg66kK46qajywFolNXpl8V0uVBVVsjaMNdSr559GhNP7bF4L2gQRM4+wDvb8HjLO1jA75Y85+6hJcJeu0DiVn1DPSxAshxp4lkY4A0QAsGn4161WswwLKo2sNJP7oKnO9u5UqQ9ZgoRzBEhw0XZtshGdD+1VQ/Loddaqju0J4kHi/MWv9yA6aNyfxowonetqZlWwrEd5yU2pBRCOFvpPuQAnHidPj5a5+EskniAKF8yMjDTm8sTHvBNhqnX4YA4OomTHK09O5f+/7WtxVAwB0eViB1uADR6gcz+mSFzDVTIHK6IoPiDyXfjaKuvInrj6AZMuWhqany3bhgKENwWyutvY3bVHNcFyOSdLFqUm7JC/eH70L2HiEXI29GmWEzaqb1rSUfJfWXfqrCo59y2mpBoLm7Yw/G2u/qeoN8PytvnJam9dYDvaxIHkKpbxhpTm7rp43Fv6QYzL7Oc8++4HCL/+NRKbipUUoo5WThVC/Qt4D5isBTg4enciRNbz5Q486siLGw4M8m6M2JFWfo/QoVakNU9Ef0PhG5blZOD5ee37BsmGAVp3/iicLbAUJah/3I9YdDq/eEoJ32aMwLpQvYa86iXQv7WYP+mqSkvyFgcmLt4R1LBnf8=
