sudo: required
dist: trusty
language: c
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_install:
- brew update
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
stages:
<<<<<<< HEAD
  - unittest
=======
  - lint
  - unittest
  - unittestandcoverage
>>>>>>> testci
  - test
  - build
jobs:
  include:
<<<<<<< HEAD
    - name: unittest
      if: branch = ci
      script:
      - yarn run unit
      - yarn run unit:coverage
    - name: test
      if: branch = ci
=======
    - name: lint
      if: branch IN (master, ci, testci)
      script:
      - yarn run lint
    - name: unittest
      if: branch IN (master)
      script:
      - yarn run clean
      - yarn run unit
    - name: unittestandcoverage
      if: branch IN (ci, testci)
      script:
      - yarn run clean
      - yarn run unit
      - yarn run unit:coverage
    - name: test
      if: branch IN (ci, testci)
>>>>>>> testci
      script: ./travis_script.sh test/features/backlog
    - script: ./travis_script.sh test/features/data_curator
    - script: ./travis_script.sh test/features/edit
    - script: ./travis_script.sh test/features/file
    - script: ./travis_script.sh test/features/find
    - script: ./travis_script.sh test/features/help
    - script: ./travis_script.sh test/features/other
    - script: ./travis_script.sh test/features/support
    - script: ./travis_script.sh test/features/tools
    - script: ./travis_script.sh test/features/window
    - name: build
<<<<<<< HEAD
      if: branch != ci
=======
      if: branch NOT IN (master, ci, testci)
>>>>>>> testci
      script: yarn run release:predraft
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - ci
  - testci
  - master
env:
  global:
    secure: F+Bn6BrNKTTybkEs4UwCl7961z7ura2zBeuw+tS/vXqswb//x9DEhEr5IJ53VyC+H2R3Wj8yJ121514FiJwNg4hUpUQ98DHyczbMLXrg+wjQI2ZYvhiAonR5LzDGNd/XLhSDezQK556+guq67SnGPP3iqnfjyu8XJ2IaynLukvLSazZTCliuqpEpwaCn99+xhaHLcGRF/Dh2Gg5+HVfQnC4S6eiYGo5Dm9RDG0hntxYHUOAxQYmnvXxf7uLNc0sfFSoVd1BZytZCVFLceY5DM0tOO8kRyMQk+LJqneAdhp9Z8pUMcTMDeJtNegqqSaBra8UAkrGv1tUrBYUQnq4fkbH0tees6mJNFkqNlOW67pj8zghYSAKwNXiazFmH/lYE2sleBKGflznLZPDD5XXLlQ/aKXF+3wAx0wMtiGkFBbGP+GoBg10+7RgKw0A+mpLaJAVwUYGGJSEfH3A0U0OEt7XRdk/sD4nFKLzL3SAx3QC57FdGu4VWdJJT9t54oX+NzM3QmBH3dNxmge4XFLR1iwN72yheB2HyGu5zafKdOfbvCz2fP1ddECm2KWu8I7NNuBIwoBUm3tVm60b3gTpblAO3RcIrLg3k+ACTSvxJuzqSIE2/YnXGnjfVPW/NaCcyD1cPFppTvmpjLNHRfwP9zeP4nBOHHgOv7grzmvCs6QY=
