sudo: required
dist: trusty
language: c
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_install:
- brew update
install:
- nvm install --lts
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
script:
- yarn run release:predraft
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
