sudo: required
dist: trusty
language: c
os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_install:
- brew update
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
# before_script:
# - yarn run lint
# - yarn run lint:test
# - yarn run test
script:
- yarn run release:pre
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - develop
