version: 1.4.{build}

# skip_non_tags: true

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

environment:
  GH_TOKEN:
    secure: 2+1HLAk/YGWqOMnjgsx5nII2huvHAlPkO24vJBqggRmcyy9FhiekaaMDTsRiRnRX
  COVERALLS_REPO_TOKEN:
    secure: 5CQKw1+Is8KphKjmT2emU/C7eNlZN3OEteemQZjOjJl47BVABYr1SOZ+IX82NSWy

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  # - choco upgrade yarn --ignore-dependencies
  - git reset --hard HEAD
  - yarn
  - node --version
  - yarn run lint
build: off
test: off
configuration: default

for:
-
  test: off
  build_script:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { yarn run release:predraft }
  configuration: release
  deploy:
    provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
-
  branches:
    only:
      - /master/
  test_script:
    - yarn run clean
    - yarn run unit
  build: off
  configuration: master
  deploy: off
-
  branches:
    only:
      - /ci/
  test_script:
    - git checkout --track origin/develop || exit
    - git checkout ci || exit
    - git merge develop || exit
    - yarn run clean
    - yarn run unit
    - yarn run pack
    - yarn run cucumber:postpack:impl
  after_test:
    - yarn run cucumber:report:badge
  build: off
  configuration: test
  deploy: off
-
  branches:
    only:
      - /testci/
  test_script:
    - yarn run clean
    - yarn run unit
    - yarn run pack
    - yarn run cucumber:postpack:impl
  build: off
  configuration: test
  deploy: off
